### PR TITLE
Fixing error on wialon execution wrapper

### PR DESCRIPTION
**Pull request by csotelo**
With this change, the wrapper works without issues

### CODE REVIEW

**Comment by ashmigelski** [comment]
Hi @csotelo

Thanks for your contribution :+1: 

Please up version to 1.1.3 in https://github.com/wialon/python-wialon/blob/master/wialon/__init__.py and then I'll merge

**Comment by csotelo** [comment]
Hi @ashmigelski I have look for that version, and  __init__.py looks appearing at 1.1.2

**Comment by ashmigelski** [comment]
Merged and updated on [PyPI](https://pypi.python.org/pypi/python-wialon/1.1.3)

**Comment by csotelo** [comment]
Great! thanks a  lot

**Pull request merged**
